main_app/urls.py
# Like Keys URL
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views
from main_app.forms import AdminAuthenticationForm


urlpatterns = [
    url(r'^admin/sign-in/$', login, {
        'authentication_form': AdminAuthenticationForm},
        name='admin_login'),

    url(r'^admin/logout/$',
    logout, name='admin_logout'),

    url(r'^$', views.root_redirect, name="root_redirect"),
    url(r'^redirect/$', views.login_redirect, name="login_redirect"),

    # Admin routes

    url(r'^admin/dashboard/$', views.admin_dashboard, name='admin_dashboard'),
    url(r'^admin/stores/$', views.admin_store_list, name='admin_store_list'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/$', views.admin_store_detail, name='admin_store_detail'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/roundups/$', views.admin_store_roundups, name='admin_store_roundups'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/transfers/$', views.admin_store_transfers, name='admin_store_transfers'),
    url(r'^admin/charity/$', views.admin_charity_list, name='admin_charity_list'),
    url(r'^admin/charity/detail/$', views.admin_charity_detail, name='admin_charity_edit'),
    url(r'^admin/charity/detail/(?P<pk>[0-9]+)/$', views.admin_charity_detail, name='admin_charity_detail'),
    url(r'^admin/transfers/$', views.admin_transfer_list, name='admin_transfer_list'),
    url(r'^admin/dev-action/$', views.dev_actions, name='dev_actions'),

    # App routes
    url(r'^(?P<store_url>[-\w]+)/$', views.order_list, name='home_page'),
    url(r'^(?P<store_url>[-\w]+)/onboarding/$', views.onboarding_wizard, name='onboarding_wizard'),
    url(r'^(?P<store_url>[-\w]+)/onboarding/confirm_install/$', views.ajax_capture_install_verification, name='ajax_capture_install_verification'),
    url(r'^(?P<store_url>[-\w]+)/request-help/$', views.ajax_help_request, name='ajax_help_request'),
    url(r'^(?P<store_url>[-\w]+)/tutorial/$', views.tutorial, name='tutorial'),
    url(r'^(?P<store_url>[-\w]+)/about/$', views.about, name='about'),
    url(r'^(?P<store_url>[-\w]+)/charity/$', views.charity_selection, name='charity_selection'),
    url(r'^(?P<store_url>[-\w]+)/charity/(?P<charity_id>[0-9]+)/toggle/$', views.ajax_toggle_charity, name="ajax_toggle_charity"),
    url(r'^(?P<store_url>[-\w]+)/contact/$', views.contact, name='contact'),
    url(r'^(?P<store_url>[-\w]+)/payment/$', views.payment_information, name='payment_information'),
    url(r'^(?P<store_url>[-\w]+)/round_up_orders/$', views.order_list, name='transaction_list'),
    url(r'^(?P<store_url>[-\w]+)/payment/history/$', views.invoice_list, name='invoice_list'),

    url(r'^api/round-up/$', views.round_up_app_proxy, name='proxy_view'),


]

vesey-setup/urls.py
import os
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from pinax.stripe.views import Webhook
import main_app.urls
import source.lib.lets_encrypt.urls


urlpatterns = [
    url(r"^payments/webhook/$", Webhook.as_view(), name="pinax_stripe_webhook"),
    url(r'login/', include('source.lib.shopify_auth.urls', namespace='shopify_auth')),
    url(r'API/', include('source.lib.shopify_webhook.urls', namespace='shopify_webhook')),
    url(r'^', include(main_app.urls, namespace='main_app')),
    url(r'^', include(source.lib.lets_encrypt.urls, namespace='lets_encrypt')),
]

# User-uploaded files like profile pics need to be served in development
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if not 'ON_PRODUCTION' in os.environ:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/views.py
from __future__ import print_function
from datetime import datetime
from decimal import Decimal, InvalidOperation
import logging
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.db import connection
from django.db.models import Sum
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django_tables2 import RequestConfig
from django_tables2.export import TableExport
from djmoney.money import Money
from pinax.stripe.actions import customers, charges, invoices
from pinax.stripe.actions.customers import get_customer_for_user
from pinax.stripe.actions.subscriptions import update
from pinax.stripe.models import Card, Subscription, Invoice, Plan, Customer
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required as default_login_required
import pytz
from stripe import InvalidRequestError
from main_app.filters import StoreFilter, CharityFilter, InvoiceFilter
from main_app.forms import StoreFilterFormHelper, CharityFilterFormHelper, TransferFilterFormHelper
from main_app.helpers.external_helpers.fixer_helper import Fixer
from main_app.helpers.external_helpers.shopify_webhook_controller import create_or_update_webhooks
from main_app.helpers.external_helpers.stripe_helper import process_stripe_user, \
    create_stripe_user_subscription, get_time_bound
from main_app.helpers.helpers import create_or_assert_round_up_product, create_or_assert_round_up_asset
from main_app.models import StoreCharityHistory, AuthAppShopUser, RoundUpOrders, Charities, UserProfile, \
    InvoiceCharityLink
from main_app.tables import StoreTable, RoundUpTable, InvoiceTable, CharityTable, AllInvoiceTable, CustomerRoundUpTable, \
    CustomerInvoiceTable
from main_app.tasks import manual_order_sync
from source.lib.pyactiveresource.connection import ResourceNotFound, UnauthorizedAccess, ClientError
from source.lib.shopify.resources.shop import Shop
from source.lib.shopify_auth.decorators import login_required, token_update_required, url_kwargs_match_request_user, \
    setup_required
from . import models
import source.lib.shopify as shopify
from . import forms


####################################
# View Definition Starts
####################################
from source.lib.shopify_webhook.decorators import app_proxy


@login_required
@url_kwargs_match_request_user
@token_update_required
def onboarding_wizard(request, *args, **kwargs):
    with request.user.session:
        template = "main_app/onboarding.html"

        if not request.user.userprofile.setup_required:
            return redirect('main_app:transaction_list', store_url=request.user.store_url_str())

        try:
            charity_instance = request.user.store_charity
        except ObjectDoesNotExist:
            charity_instance = StoreCharityHistory(store=request.user)

        STRIPE_PUBLIC_KEY = settings.PINAX_STRIPE_PUBLIC_KEY

        # Get all current global charities
        all_charities = Charities.objects.exclude(charity_logo='').order_by('name')

        if request.method == "POST":

            stripe_customer = process_stripe_user(request.user, request.POST.get('stripeToken', None))

            if stripe_customer:
                create_stripe_user_subscription(store=request.user, stripe_customer=stripe_customer)
                request.user.userprofile.setup_required = False
                request.user.userprofile.save()

                messages.success(request, "The payment method was set.")
                return redirect('main_app:transaction_list', store_url=request.user.store_url_str())
            else:
                messages.error(request, "There was an issue with your payment method.")

        return render(request, template, {'all_charities': all_charities,
                                              'charity_instance': charity_instance, 'STRIPE_PUBLIC_KEY': STRIPE_PUBLIC_KEY})


@login_required
@url_kwargs_match_request_user
@token_update_required
@setup_required
def tutorial(request, *args, **kwargs):
    with request.user.session:

        active_charity_count = Charities.objects.exclude(charity_logo='').count()

        return render(request, "main_app/tutorial.html", {'active_charity_count': active_charity_count})


@login_required
@url_kwargs_match_request_user
@token_update_required
@setup_required
def charity_selection(request, *args, **kwargs):
    with request.user.session:
        template = "main_app/charities.html"

        try:
            charity_instance = request.user.store_charity
        except ObjectDoesNotExist:
            charity_instance = StoreCharityHistory(store=request.user)

        # Get all current global charities
        all_charities = Charities.objects.exclude(charity_logo='').order_by('name')

        return render(request, template, {'all_charities': all_charities,
                                              'charity_instance': charity_instance})


@login_required
@url_kwargs_match_request_user
@token_update_required
def contact(request, *args, **kwargs):
    with request.user.session:
        template = "main_app/contact.html"

        if request.method == "POST":
            contact_form = forms.ContactForm(request.POST)

            if not contact_form.is_valid():
                return render(request, template, {"contact_form":contact_form})

            if contact_form.is_valid():

                try:
                    email = request.user.userprofile.shop_contact_email
                except ObjectDoesNotExist:
                    email = settings.PINAX_STRIPE_INVOICE_FROM_EMAIL

                ctx = {
                    "myshopify_domain": request.user.myshopify_domain,
                    "message": str(contact_form.cleaned_data['message']),
                    "phone_number": str(contact_form.cleaned_data.get('phone_number', None)),
                    "full_name": str(contact_form.cleaned_data.get('full_name', None)),
                    "customer_email": str(email)
                }
                subject = render_to_string("main_app/email/contact_subject.txt", ctx)
                subject = subject.strip()
                message = render_to_string("main_app/email/contact_body.txt", ctx)

                EmailMessage(
                    subject,
                    message,
                    to=[settings.HELP_TO_MAILBOX_EMAIL],
                    reply_to=[email],
                    from_email=settings.PINAX_STRIPE_INVOICE_FROM_EMAIL,
                ).send()

                messages.success(request, "Your support message was sent.")
                return redirect('main_app:home_page', store_url=request.user.store_url_str())

        else:
            contact_form = forms.ContactForm()

            return render(request, template, {"contact_form":contact_form})

        return render(request, template,)


@login_required
@url_kwargs_match_request_user
@token_update_required
def about(request, *args, **kwargs):
    with request.user.session:
        return render(request, "main_app/about.html",)


@login_required
@url_kwargs_match_request_user
@token_update_required
@setup_required
def payment_information(request, *args, **kwargs):

    with request.user.session:

        # Get the current stores stripe customer info.
        stripe_customer = get_customer_for_user(request.user)
        # Get all the current customers/stores payment methods
        cards = Card.objects.filter(customer=stripe_customer).order_by("created_at")

        STRIPE_PUBLIC_KEY = settings.PINAX_STRIPE_PUBLIC_KEY

        if request.method == "POST":

            stripe_customer = process_stripe_user(request.user, request.POST.get('stripeToken', None), existing_cards=cards)
            create_stripe_user_subscription(store=request.user, stripe_customer=stripe_customer)

            messages.success(request, "The payment method was changed.")
            return redirect('main_app:payment_information', store_url=request.user.store_url_str())

        return render(request, "main_app/payment_information.html", {'cards':cards, 'STRIPE_PUBLIC_KEY': STRIPE_PUBLIC_KEY} )


@login_required
@url_kwargs_match_request_user
@token_update_required
@setup_required
def order_list(request, *args, **kwargs):

    with request.user.session:
        template = "main_app/order_list.html"

        # Get dashboard details
        round_up_count = RoundUpOrders.objects.exclude(
            shopify_payment_status=RoundUpOrders.SHOPIFY_PAYMENT_STATUS.REFUNDED).filter(store=request.user).count()

        round_up_total = [
            Money(data['order_roundup_total__sum'], data['order_roundup_total_currency']) for data in
            RoundUpOrders.objects.exclude(
            shopify_payment_status=RoundUpOrders.SHOPIFY_PAYMENT_STATUS.REFUNDED).filter(store=request.user).values(
                'order_roundup_total_currency').annotate(Sum('order_roundup_total')).order_by()
        ]

        if round_up_total and len(round_up_total) == 1:
            round_up_total = round_up_total[0]
        else:
            round_up_total = Money(0.0, settings.DEFAULT_CURRENCY)

        table = CustomerRoundUpTable(RoundUpOrders.objects.filter(store=request.user).order_by('-shopify_created_at'))

        RequestConfig(request, paginate={'per_page': 50}).configure(table)

        return render(request, template, {
            'table': table,
            'round_up_count': round_up_count,
            'round_up_total': round_up_total
        })


@login_required
@url_kwargs_match_request_user
@token_update_required
@setup_required
def invoice_list(request, *args, **kwargs):

    with request.user.session:

        template = "main_app/invoice_list.html"

main_app/templates/main_app/about.html
{% extends "_base.html" %}
{% load staticfiles %}
{% block headerpagetitle %}About us{% endblock headerpagetitle %}

{% block headerbuttons %}

primary: {"label":"Setup Instructions","target":"app","href":"{% url 'main_app:tutorial' store_url=request.user.store_url_str %}"},
secondary: [{"label":"My Charity Orders","target":"app","href":"{% url 'main_app:transaction_list' store_url=request.user.store_url_str %}"},
{"label":"Charity Settings","target":"app","href":"{% url 'main_app:charity_selection' store_url=request.user.store_url_str %}"},
{"label":"Payment Settings","target":"app","href":"{% url 'main_app:payment_information' store_url=request.user.store_url_str %}"},
{ "label": "•••",
                type: "dropdown",
                links: [
                         {"label":"About Vesey","target":"app","href":"{% url 'main_app:about' store_url=request.user.store_url_str %}"},
                         {"label":"Contact us","target":"app","href":"{% url 'main_app:contact' store_url=request.user.store_url_str %}"},
                         {"label":"Installation instructions","target":"app","href":"{% url 'main_app:tutorial' store_url=request.user.store_url_str %}"},
                       ]
            }]
{% endblock headerbuttons %}

{% block headerbread %}
{% endblock headerbread %}

{% block styles %}

{% endblock styles %}

{% load crispy_forms_tags %}

{% block extrahead %}
{% endblock extrahead %}

{% block shopifyhead %}
{% endblock shopifyhead %}

{% block extra_messages %}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="page-header">
            <h1><img src="{% static 'site/images/logo.png' %}"> <small>About Us Page</small></h1>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="row">

                    <div class="col-xs-12">
                        <p>The Vesey Foundation is a 501(c)3 organization that works to empower innovative non-profits around the world.</p>
                    </div>
                    <div class="col-xs-12">
                        <p>The Round Up program was developed to provide a steady stream of income to our charitable partners so that they can exponentially improve their results. Thanks to a generous endowment, this program comes at no cost to you and 100% of all donations collected through the Round Up program are passed onto our nonprofit partners.</p>
                    </div>
                    <div class="col-xs-12">
                        <p>Below you will find answers to commonly asked questions. If you have any additional questions please feel free to contact us here.</p>
                    </div>
                    <hr>
                    <div class="col-xs-12">
                        <h3>What is the Change for Change program?</h3>
                        <p>The Change for Change program is the 21st century version of a donation collection box. Instead of customers dropping spare change into a penny jar on the countertop, they can instead donate a few cents directly from their credit card.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>Who is the Vesey Foundation?</h3>
                        <p>The Vesey Foundation is a 501(c)3 non-profit organization based in New York with a global focus.</p>
                        <br>
                        <p>The Vesey Foundation supports innovative solutions to global problems. Through our partners, we have pursued advancements in medical technologies, expanded STEM education in the United States and abroad, and provides access to clean energy worldwide.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>Where does my donation go?</h3>
                        <p>The Vesey Foundation works with a variety of accredited non-profit partner organizations such as The American Cancer Society, Charity:Water, and New York on Tech.</p>
                        <br>
                        <p>We also work with our ecommerce partners to continuously expand the organizations we support. We donate on your behalf to any particular charity or cause that you are passionate about.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>How much of my donation actually goes to the intended cause?</h3>
                        <p>All of it! 100% of all donations go directly to selected causes.</p>
                        <br>
                        <p>How is this possible? Our corporate sponsors and endownment subsidize all operating expenses so that we can distribute all donations directly to these remarkable initiatives.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>Will my customers support this?</h3>
                        <p>Yes! We have conducted independent studies and pilot programs to ensure that your customers fully support this initiative and approve of your restaurant for participating. We provide you with simple informational materials so your customers understand the program, how to participate, and the value your business provides.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>What does it cost to participate?</h3>
                        <p>Nothing! The Vesey Foundations covers all costs related to integrating your existing POS system with the Change for Change software and provides all marketing collateral for your business. You just have to take a few minutes to train your staff with this new POS functionality.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>What is the time commitment?</h3>
                        <p>Just a few minutes each month! Once you are set up the only time commitment is teaching your staff about this new functionality, which typically only takes a few minutes.</p>
                        <br>
                        <p>We can also provide a representative to prepare your staff for the launch of this program at no cost to you. The only other time commitment involves distributing the total donations to the Vesey Foundation each month by check, credit card, PayPal or bank transfer.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>How does the technology work?</h3>
                        <p>We work directly with your current Point-of-Sale (POS) or payment processing system to implement the necessary changes to make the launch of the Change for Change program completely seamless for your staff.</p>
                        <br>
                        <p>One of our representatives will handle this integration in less than one hour without interfering with normal business operations. From there on, the check out process will automatically ask customers if they want to "round up" their total purchase amount.</p>
                        <br>
                        <p>Sales reports will state exactly how much of the round up donations were collected in a given time period.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>How will the new checkout page look?</h3>
                        <p>Each website may have a slightly different look, but it is always generally the same. Below is a sample of what the checkout looks for Shopify websites:</p>
                        <br>
                    </div>
                    <div class="col-xs-12">
                        <img class="img-thumbnail img-responsive" src="{% static 'site/images/E-commerce_round_up.jpg' %}">
                    </div>
                    <div class="col-xs-12">
                        <h3>Can I write off the donations as a tax-deductible?</h3>
                        <p>Yes! We will send you a form that verifies that your donation is tax-deductible up to the maximum amount allowed by law.</p>
                    </div>
                    <div class="col-xs-12">
                        <h3>How does the signup process work?</h3>
                        <p>Just contact us by phone, email, or through our website to begin the setup process. A representative will get in touch by phone or in-person to answer any questions you may have and schedule a time to begin the system integration. That’s it!</p>
                    </div>
                </div>

            </div>
        </div>

    </div>

</div>
{% endblock %}


{% block beaconsuggest %}
{% endblock beaconsuggest %}

{% block scripts %}

{% endblock %}

main_app/templates/main_app/admin_blank.html
{% extends "_admin_base.html" %}
{% load staticfiles %}
{% block headerpagetitle %}Dev list{% endblock headerpagetitle %}

{% block headerbread %}
{% endblock headerbread %}

{% block styles %}
{% endblock styles %}

{% block pagespecificstyles %}
{% endblock pagespecificstyles %}

{% load crispy_forms_tags %}

{% block extrahead %}
{% endblock extrahead %}

{% block shopifyhead %}
{% endblock shopifyhead %}

{% block extra_messages %}
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Dev stuff" "main_app:dev_actions" %}
{% endblock %}

{% block body %}

<div class="panel panel-default">
  <div class="panel-heading">
      <div class="row clearfix">
          Dev actions
      </div>
  </div>

  <div class="panel-body">
    NOTHING!
  </div>
</div>

{% endblock %}

{% block pagespecificjs %}
{% endblock pagespecificjs %}

{% block scripts %}
{% endblock %}

main_app/templates/main_app/admin_store_transfers.html
{% extends "_admin_base.html" %}
{% load staticfiles %}
{% block headerpagetitle %}{{ store.userprofile.name}} Invoices{% endblock headerpagetitle %}

{% block headerbread %}
{% endblock headerbread %}

{% block styles %}
{% endblock styles %}

{% block pagespecificstyles %}
{% endblock pagespecificstyles %}

{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load stripe_tags %}

{% block extrahead %}
{% endblock extrahead %}

{% block shopifyhead %}
{% endblock shopifyhead %}

{% block extra_messages %}
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Stores" "main_app:admin_store_list" %}
    {% breadcrumb store.userprofile.name "#" %}
{% endblock %}

{% block body %}

<div class="panel panel-default">
  <div class="panel-heading clearfix">

      <div class="row">
          <div class="col-xs-12 col-sm-6">
              <div class="tabbable-line">
                  <ul class="nav nav-tabs">
                      <li>
                          <a href="{% url 'main_app:admin_store_detail' pk=store.id %}">Details</a>
                      </li>
                      <li >
                          <a href="{% url 'main_app:admin_store_roundups' pk=store.id %}">Roundups</a>
                      </li>
                      <li class="active">
                          <a href="#">Invoices</a>
                      </li>
                  </ul>
              </div>
          </div>

          <div class="col-xs-12 col-sm-6">
              <h3 class="pull-right store-status-label">
                  {% if store.active_installation %}
                  <span class="label label-success">Shopify: Active</span>
                  {% else %}
                  <span class="label label-default">Shopify: Inactive</span>
                  {% endif %}

                  {{ store | stripe_sub_status |safe }}
              </h3>
          </div>
      </div>

  </div>

  <div class="panel-body">
    {% render_table table %}
  </div>
</div>

{% endblock %}

{% block pagespecificjs %}
{% endblock pagespecificjs %}

{% block scripts %}
{% endblock %}

main_app/templates/main_app/charities.html
{% extends "_base.html" %}
{% load staticfiles %}
{% block headerpagetitle %}Charity selection{% endblock headerpagetitle %}

{% block headerbuttons %}
primary: {"label":"Setup Instructions","target":"app","href":"{% url 'main_app:tutorial' store_url=request.user.store_url_str %}"},
secondary: [{"label":"My Charity Orders","target":"app","href":"{% url 'main_app:transaction_list' store_url=request.user.store_url_str %}"},
{"label":"Charity Settings","target":"app","href":"{% url 'main_app:charity_selection' store_url=request.user.store_url_str %}"},
{"label":"Payment Settings","target":"app","href":"{% url 'main_app:payment_information' store_url=request.user.store_url_str %}"},
{ "label": "•••",
                type: "dropdown",
                links: [
                         {"label":"About Vesey","target":"app","href":"{% url 'main_app:about' store_url=request.user.store_url_str %}"},
                         {"label":"Contact us","target":"app","href":"{% url 'main_app:contact' store_url=request.user.store_url_str %}"},
                         {"label":"Installation instructions","target":"app","href":"{% url 'main_app:tutorial' store_url=request.user.store_url_str %}"},
                       ]
            }]
{% endblock headerbuttons %}

{% block headerbread %}
{% endblock headerbread %}

{% block styles %}

{% endblock styles %}

{% load thumbnail %}

{% block extrahead %}
{% endblock extrahead %}

{% block shopifyhead %}
{% endblock shopifyhead %}

{% block extra_messages %}
{% endblock %}

{% block body %}
    <div id="overlay"></div>
    <div class="container">
        <div class="page-header">
            <h1><img src="{% static 'site/images/logo.png' %}"> <small>Charity selection</small></h1>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="row">

                    <div class="col-xs-12">
                        <p>We are proud to support innovative nonprofit organizations around the world. All donations raised through this round up program are passed on to our charity partners. During setup you will be able to choose which charity your store will support.</p>
                        <p>If you are interested in submitting a new charity for review please <a href="{% url 'main_app:contact' store_url=request.user.store_url_str %}">contact us here</a>.</p>
                    </div>

                    <div class="col-xs-12">
                        <hr>
                        <h2>Your current charity: {% if charity_instance.selected_charity %}<span class="label label-success" id="charity-label">{{ charity_instance.selected_charity.name }}</span>{%else%}<span class="label label-default" id="charity-label">Not set</span>{%endif%}</h2>
                    </div>

                </div>

                {% include 'main_app/charity_table.html' %}

            </div>
        </div>

    </div>
{% endblock %}

{% block beaconsuggest %}
{% endblock beaconsuggest %}

{% block scripts %}
<script type="text/javascript" src='{% static "site/js/charity_selector.js" %}'></script>
{% endblock %}

main_app/templates/main_app/contact.html
{% extends "_base.html" %}
{% load staticfiles %}
{% block headerpagetitle %}Contact us{% endblock headerpagetitle %}

{% block headerbuttons %}
primary: {"label":"Setup Instructions","target":"app","href":"{% url 'main_app:tutorial' store_url=request.user.store_url_str %}"},
secondary: [{"label":"My Charity Orders","target":"app","href":"{% url 'main_app:transaction_list' store_url=request.user.store_url_str %}"},
{"label":"Charity Settings","target":"app","href":"{% url 'main_app:charity_selection' store_url=request.user.store_url_str %}"},
{"label":"Payment Settings","target":"app","href":"{% url 'main_app:payment_information' store_url=request.user.store_url_str %}"},
{ "label": "•••",
                type: "dropdown",
                links: [
                         {"label":"About Vesey","target":"app","href":"{% url 'main_app:about' store_url=request.user.store_url_str %}"},
                         {"label":"Contact us","target":"app","href":"{% url 'main_app:contact' store_url=request.user.store_url_str %}"},
                         {"label":"Installation instructions","target":"app","href":"{% url 'main_app:tutorial' store_url=request.user.store_url_str %}"},
                       ]
            }]
{% endblock headerbuttons %}

{% block headerbread %}
{% endblock headerbread %}

{% block styles %}

{% endblock styles %}

{% load crispy_forms_tags %}

{% block extrahead %}
{% endblock extrahead %}

{% block shopifyhead %}
{% endblock shopifyhead %}

{% block extra_messages %}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="page-header">
            <h1><img src="{% static 'site/images/logo.png' %}"> <small>Contact Us</small></h1>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="row">

                    <div class="col-xs-12">
                        <p>Please feel free to contact us directly using the form below for all questions and requests, including:</p>
                        <ul>
                            <li>Technical support</li>
                            <li>Request a free set up</li>
                            <li>Submit a new charity partner</li>
                        </ul>
                        <p>A dedicated team member will respond within one (1) hour of your message.</p>
                    </div>

                    <form method="post" action="" class="">{% csrf_token %}
                    <div class="col-xs-12">
                        {% crispy contact_form %}
                        <button type="submit" class="btn btn-primary pull-right">Send</button>
                    </div>
                    </form>

                </div>

            </div>
        </div>

    </div>
{% endblock %}

{% block beaconsuggest %}
{% endblock beaconsuggest %}

{% block scripts %}

{% endblock %}

main_app/templates/main_app/empty.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
asdasdasd
</body>
</html>