main_app/urls.py
# Like Keys URL
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views
from main_app.forms import AdminAuthenticationForm


urlpatterns = [
    url(r'^admin/sign-in/$', login, {
        'authentication_form': AdminAuthenticationForm},
        name='admin_login'),

    url(r'^admin/logout/$',
    logout, name='admin_logout'),

    url(r'^$', views.root_redirect, name="root_redirect"),
    url(r'^redirect/$', views.login_redirect, name="login_redirect"),

    # Admin routes

    url(r'^admin/dashboard/$', views.admin_dashboard, name='admin_dashboard'),
    url(r'^admin/stores/$', views.admin_store_list, name='admin_store_list'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/$', views.admin_store_detail, name='admin_store_detail'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/roundups/$', views.admin_store_roundups, name='admin_store_roundups'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/transfers/$', views.admin_store_transfers, name='admin_store_transfers'),
    url(r'^admin/charity/$', views.admin_charity_list, name='admin_charity_list'),
    url(r'^admin/charity/detail/$', views.admin_charity_detail, name='admin_charity_edit'),
    url(r'^admin/charity/detail/(?P<pk>[0-9]+)/$', views.admin_charity_detail, name='admin_charity_detail'),
    url(r'^admin/transfers/$', views.admin_transfer_list, name='admin_transfer_list'),
    url(r'^admin/dev-action/$', views.dev_actions, name='dev_actions'),

    # App routes
    url(r'^(?P<store_url>[-\w]+)/$', views.order_list, name='home_page'),
    url(r'^(?P<store_url>[-\w]+)/onboarding/$', views.onboarding_wizard, name='onboarding_wizard'),
    url(r'^(?P<store_url>[-\w]+)/onboarding/confirm_install/$', views.ajax_capture_install_verification, name='ajax_capture_install_verification'),
    url(r'^(?P<store_url>[-\w]+)/request-help/$', views.ajax_help_request, name='ajax_help_request'),
    url(r'^(?P<store_url>[-\w]+)/tutorial/$', views.tutorial, name='tutorial'),
    url(r'^(?P<store_url>[-\w]+)/about/$', views.about, name='about'),
    url(r'^(?P<store_url>[-\w]+)/charity/$', views.charity_selection, name='charity_selection'),
    url(r'^(?P<store_url>[-\w]+)/charity/(?P<charity_id>[0-9]+)/toggle/$', views.ajax_toggle_charity, name="ajax_toggle_charity"),
    url(r'^(?P<store_url>[-\w]+)/contact/$', views.contact, name='contact'),
    url(r'^(?P<store_url>[-\w]+)/payment/$', views.payment_information, name='payment_information'),
    url(r'^(?P<store_url>[-\w]+)/round_up_orders/$', views.order_list, name='transaction_list'),
    url(r'^(?P<store_url>[-\w]+)/payment/history/$', views.invoice_list, name='invoice_list'),

    url(r'^api/round-up/$', views.round_up_app_proxy, name='proxy_view'),


]

source/lib/shopify_auth/urls.py
from django.conf.urls import url

from source.lib.shopify_auth import views

urlpatterns = [
  url(r'^finalize/$',     views.finalize, name='finalize'),
  url(r'^authenticate/$', views.authenticate, name='authenticate'),
  url(r'^$',              views.login, name='login'),
]

vesey-setup/urls.py
import os
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from pinax.stripe.views import Webhook
import main_app.urls
import source.lib.lets_encrypt.urls


urlpatterns = [
    url(r"^payments/webhook/$", Webhook.as_view(), name="pinax_stripe_webhook"),
    url(r'login/', include('source.lib.shopify_auth.urls', namespace='shopify_auth')),
    url(r'API/', include('source.lib.shopify_webhook.urls', namespace='shopify_webhook')),
    url(r'^', include(main_app.urls, namespace='main_app')),
    url(r'^', include(source.lib.lets_encrypt.urls, namespace='lets_encrypt')),
]

# User-uploaded files like profile pics need to be served in development
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if not 'ON_PRODUCTION' in os.environ:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/lib/shopify_auth/models.py
import source.lib.shopify as shopify
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import logging


class ShopUserManager(BaseUserManager):

    def create_user(self, myshopify_domain, domain, password=None):
        """
        Creates and saves a ShopUser with the given domains and password.
        """
        if not myshopify_domain:
            raise ValueError('ShopUsers must have a myshopify domain')

        user = self.model(myshopify_domain=myshopify_domain, domain=domain)

        # Never want to be able to log on externally.
        # Authentication will be taken care of by Shopify OAuth.
        user.set_unusable_password()
        user.save(using=self._db)
        return user

    def create_superuser(self, myshopify_domain, domain, password):
        """
        Creates and saves a ShopUser with the given domains and password.
        """
        return self.create_user(myshopify_domain, domain, password)


@python_2_unicode_compatible
class AbstractShopUser(AbstractBaseUser):
    myshopify_domain = models.CharField(max_length=255, unique=True, editable=False)
    token = models.CharField(max_length=32, editable=False, default='00000000000000000000000000000000')

    objects = ShopUserManager()

    USERNAME_FIELD = 'myshopify_domain'

    @property
    def session(self):
        return shopify.Session.temp(self.myshopify_domain, self.token)

    def get_full_name(self):
        return self.myshopify_domain

    def get_short_name(self):
        return self.myshopify_domain

    def __str__(self):
        return self.get_full_name()

    class Meta:
        abstract = True

source/lib/shopify_auth/views.py
from base64 import b64encode
from os import urandom
from django.conf import settings
from django.contrib import auth
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, resolve_url, get_object_or_404, redirect
import source.lib.shopify as shopify
from .decorators import anonymous_required, login_required, url_kwargs_match_request_user, token_update_required
from django.core.cache import cache
import logging
from urlparse import urlparse, parse_qs
from source.lib.shopify_auth.helpers import add_query_parameters_to_url
from source.lib.shopify_auth.backends import ShopUserBackend


def get_return_address(request):
    shop_param = {}
    shop = getattr(request.user, "myshopify_domain", None)
    if shop:
        shop_param = {"shop" : shop}

    host = request.META.get("HTTP_HOST", None)
    referrer = request.META.get("HTTP_REFERER", None)

    if referrer:
        referrer = urlparse(referrer)

        if referrer.netloc.lower() == host.lower():
            query = parse_qs(referrer.query)
            redirect = query.get(auth.REDIRECT_FIELD_NAME, [""])[0]
            if redirect:
                return add_query_parameters_to_url(redirect, shop_param)

    return add_query_parameters_to_url(resolve_url(settings.LOGIN_REDIRECT_URL), shop_param)


def create_nonce(length=64):
    return filter(lambda s: s.isalpha(), b64encode(urandom(length * 2)))[:length]


@anonymous_required
def login(request, *args, **kwargs):

    # The `shop` parameter may be passed either directly in query parameters, or
    # as a result of submitting the login form.
    shop = request.POST.get('shop', request.GET.get('shop'))
    # If the shop parameter has already been provided, attempt to authenticate immediately.
    if shop:
        return authenticate(request, *args, **kwargs)

    # Get the current Shopify App Store URL
    SHOPIFY_APP_STORE_URL = settings.SHOPIFY_APP_STORE_URL
    APP_MARKETING_URL = settings.APP_MARKETING_URL

    return render(request, "shopify_auth/login.html", {
        'SHOPIFY_APP_NAME': settings.SHOPIFY_APP_NAME,
        'SHOPIFY_APP_STORE_URL': SHOPIFY_APP_STORE_URL,
        'APP_MARKETING_URL': APP_MARKETING_URL
    })


@anonymous_required
def authenticate(request, *args, **kwargs):

    shop = request.POST.get('shop', request.GET.get('shop'))

    if shop:
        redirect_uri = request.build_absolute_uri(reverse('shopify_auth:finalize'))

        scope = settings.SHOPIFY_APP_API_SCOPE

        # Create a state nonce
        temp_nonce = create_nonce()

        # Store the nonce in memcache to check later (for this user/shop)
        if 'https://' in shop.lower():
            shop = shop[8:]
        elif 'http://' in shop.lower():
            shop = shop[7:]
        elif '.myshopify.com' not in shop.lower():
            return HttpResponseRedirect(reverse('shopify_auth:login'))

        # Store the nonce in memcache to check later (for this user/shop)
        key_name = str(shop) + "_nonce"
        cache.set(key=key_name, value=temp_nonce, timeout=600)

        permission_url = shopify.Session(shop.strip()).create_permission_url(scope, redirect_uri, state=temp_nonce)

        if settings.SHOPIFY_APP_IS_EMBEDDED:
            # Embedded Apps should use a Javascript redirect.
            return render(request, "shopify_auth/iframe_redirect.html", {
                'shop': shop,
                'redirect_uri': permission_url
            })
        else:
            # Non-Embedded Apps should use a standard redirect.
            return HttpResponseRedirect(permission_url)
    else:
        shop = request.GET.get('shop')
        if shop:
            return finalize(request, *args, **kwargs)

    return_address = get_return_address(request)
    return HttpResponseRedirect(return_address)


@anonymous_required
def finalize(request, *args, **kwargs):
    shop = request.POST.get('shop', request.GET.get('shop'))

    state = request.GET.get('state', None)
    key_name = str(shop) + "_nonce"
    original_nonce = cache.get(key_name)

    if not state or not original_nonce or state != original_nonce:
        logging.error('OAUTH-FINALIZE-FOR-{0}: There was an issue with the state of this request.'.format(shop))
        login_url = reverse('shopify_auth:login')
        return HttpResponseRedirect(login_url)

    try:
        shopify_session = shopify.Session(shop, token=kwargs.get('token'))
        shopify_session.request_token(request.GET)
    except Exception as e:
        login_url = reverse('shopify_auth:login')
        return HttpResponseRedirect(login_url)

    # Attempt to authenticate the user and log them in.
    user = auth.authenticate(myshopify_domain=shopify_session.url, token=shopify_session.token)

    if user:

        auth.login(request, user)
        return redirect(reverse("main_app:home_page", kwargs={'store_url': user.store_url_str()}) )

    login_url = reverse('shopify_auth:login')
    return HttpResponseRedirect(login_url)

source/lib/shopify_auth/templates/shopify_auth/confirm.html
some random stuff

source/lib/shopify_auth/templates/shopify_auth/iframe_redirect.html
<script type="text/javascript">
  // If the current window is the 'parent', change the URL by setting location.href
  if (window.top == window.self) {
    window.top.location.href = "{{ redirect_uri }}";
  // If the current window is the 'child', change the parent's URL with postMessage
  } else {
    var normalizedLink = document.createElement('a');
    normalizedLink.href = "{{ redirect_uri }}";
    var message = JSON.stringify({
      message: "Shopify.API.remoteRedirect",
      data: { location: normalizedLink.href }
    });
    window.parent.postMessage(message, "https://{{ shop }}");
  }
</script>

source/lib/shopify_auth/templates/shopify_auth/login.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load crispy_forms_tags %}
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Made by Anli Zaimi at http://azmind.com, Borrowed and changed by Solvecore .Inc">
        <link rel="shortcut icon" href="{% static 'site/ico/favicon.png' %}">
         <title>{% block title %}{% include "_brandname.html" %}{% endblock %}</title>

        <!-- CSS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link href="{% static 'site/css/login-page-style.css' %}" rel="stylesheet">

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'site/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <!-- Top content -->
        <div class="top-content">

            <div class="inner-bg">
                <div class="container">

                    <div class="row">

                        <div class="col-sm-8 col-sm-offset-2 col-md-offset-2 col-lg-offset-2 text logo-header">
                            <img src="{% static 'site/images/logo.png' %}" class="img-responsive logo-header__img">
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-sm-6 text marketing-text__container">
                            <h1 class="wow fadeInLeftBig">Whats your <strong>NextOffer?</strong></h1>
                            <div class="description wow fadeInLeftBig">
                            	<p>
	                            	{% lorem 20 w %}
                            	</p>
                            </div>
                            <div class="top-big-link wow fadeInUp">
                            	<a class="btn btn-link-2 scroll-link" href="{{ APP_MARKETING_URL }}">Learn more</a>
                            </div>
                        </div>

                        <div class="col-sm-1 middle-border"></div>
                        <div class="col-sm-1"></div>

                        <div class="col-sm-5">

                        	<div class="form-box">
	                        	<div class="form-top">
	                        		<div class="form-top-left">
	                        			<h3>Login to the app</h3>
{#	                            		<p>Enter your myshopify.com domain:</p>#}
                                        <p>Install {% include "_brandname.html" %} today to boost conversions:</p>
	                        		</div>
	                        		<div class="form-top-right">
	                        			<i class="fa fa-key"></i>
	                        		</div>
	                            </div>
	                            <div class="form-bottom">
                                    <form id="login-form" method="POST" action="{% url 'shopify_auth:authenticate' %}">
                                        {% csrf_token %}
                                        <div class="input-group">
                                          <input id="shop" name="shop" type="text" class="form-control" placeholder="Your myshopify.com domain...">
                                          <span class="input-group-btn">
                                            <button class="btn btn-secondary" id="submit-login">Install</button>
                                          </span>
                                        </div>
                                    </form>
			                    </div>

		                    </div>

                        </div>
                    </div>

                </div>
            </div>

        </div>

        <!-- Javascript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script>window.jQuery || document.write(unescape('<script src="{% static 'js/jquery.min.js' %}"><\/script>'))</script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="{% static 'site/js/ie10-viewport-bug-workaround.js' %}"></script>

        <script src="{% static 'site/js/jquery.backstretch.min.js' %}"></script>
        <script>
        jQuery(document).ready(function() {
	            $.backstretch("{% static 'site/images/bg_img.png' %}");
        });
        </script>

        <script>
            $("#submit-login").click(function(ev) {
                $('#login-form').append('<input type="hidden" name="login-post-form" id="login-post-form" value="login-post-form" />').submit();
            });
        </script>

        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>