main_app/urls.py
# Like Keys URL
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views
from main_app.forms import AdminAuthenticationForm


urlpatterns = [
    url(r'^admin/sign-in/$', login, {
        'authentication_form': AdminAuthenticationForm},
        name='admin_login'),

    url(r'^admin/logout/$',
    logout, name='admin_logout'),

    url(r'^$', views.root_redirect, name="root_redirect"),
    url(r'^redirect/$', views.login_redirect, name="login_redirect"),

    # Admin routes

    url(r'^admin/dashboard/$', views.admin_dashboard, name='admin_dashboard'),
    url(r'^admin/stores/$', views.admin_store_list, name='admin_store_list'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/$', views.admin_store_detail, name='admin_store_detail'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/roundups/$', views.admin_store_roundups, name='admin_store_roundups'),
    url(r'^admin/stores/(?P<pk>[0-9]+)/transfers/$', views.admin_store_transfers, name='admin_store_transfers'),
    url(r'^admin/charity/$', views.admin_charity_list, name='admin_charity_list'),
    url(r'^admin/charity/detail/$', views.admin_charity_detail, name='admin_charity_edit'),
    url(r'^admin/charity/detail/(?P<pk>[0-9]+)/$', views.admin_charity_detail, name='admin_charity_detail'),
    url(r'^admin/transfers/$', views.admin_transfer_list, name='admin_transfer_list'),
    url(r'^admin/dev-action/$', views.dev_actions, name='dev_actions'),

    # App routes
    url(r'^(?P<store_url>[-\w]+)/$', views.order_list, name='home_page'),
    url(r'^(?P<store_url>[-\w]+)/onboarding/$', views.onboarding_wizard, name='onboarding_wizard'),
    url(r'^(?P<store_url>[-\w]+)/onboarding/confirm_install/$', views.ajax_capture_install_verification, name='ajax_capture_install_verification'),
    url(r'^(?P<store_url>[-\w]+)/request-help/$', views.ajax_help_request, name='ajax_help_request'),
    url(r'^(?P<store_url>[-\w]+)/tutorial/$', views.tutorial, name='tutorial'),
    url(r'^(?P<store_url>[-\w]+)/about/$', views.about, name='about'),
    url(r'^(?P<store_url>[-\w]+)/charity/$', views.charity_selection, name='charity_selection'),
    url(r'^(?P<store_url>[-\w]+)/charity/(?P<charity_id>[0-9]+)/toggle/$', views.ajax_toggle_charity, name="ajax_toggle_charity"),
    url(r'^(?P<store_url>[-\w]+)/contact/$', views.contact, name='contact'),
    url(r'^(?P<store_url>[-\w]+)/payment/$', views.payment_information, name='payment_information'),
    url(r'^(?P<store_url>[-\w]+)/round_up_orders/$', views.order_list, name='transaction_list'),
    url(r'^(?P<store_url>[-\w]+)/payment/history/$', views.invoice_list, name='invoice_list'),

    url(r'^api/round-up/$', views.round_up_app_proxy, name='proxy_view'),


]

vesey-setup/urls.py
import os
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from pinax.stripe.views import Webhook
import main_app.urls
import source.lib.lets_encrypt.urls


urlpatterns = [
    url(r"^payments/webhook/$", Webhook.as_view(), name="pinax_stripe_webhook"),
    url(r'login/', include('source.lib.shopify_auth.urls', namespace='shopify_auth')),
    url(r'API/', include('source.lib.shopify_webhook.urls', namespace='shopify_webhook')),
    url(r'^', include(main_app.urls, namespace='main_app')),
    url(r'^', include(source.lib.lets_encrypt.urls, namespace='lets_encrypt')),
]

# User-uploaded files like profile pics need to be served in development
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if not 'ON_PRODUCTION' in os.environ:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/403_csrf.html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" media="screen" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" media="screen" rel="stylesheet" />

    <script type="text/javascript" src="https://cdn.shopify.com/s/assets/external/app.js"></script>
    <script type="text/javascript">
        ShopifyApp.init({
            apiKey: '{{ SHOPIFY_APP_API_KEY }}',
            shopOrigin: 'https://{{ user.myshopify_domain }}'
        });
        ShopifyApp.ready(function() {
            ShopifyApp.Bar.initialize({
                title: '{{ SHOPIFY_APP_NAME }}',
                buttons: {}
            });

            {% block shopifyhead %}{% endblock shopifyhead %}

        });
    </script>

    <style>
      *{-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box}html,body,div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,caption,article,aside,canvas,details,figcaption,figure,footer,header,hgroup,menu,nav,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;outline:0;vertical-align:baseline;background:transparent}article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}html{font-size:16px;line-height:24px;width:100%;height:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;overflow-y:scroll;overflow-x:hidden}img{vertical-align:middle;max-width:100%;height:auto;border:0;-ms-interpolation-mode:bicubic}body{min-height:100%;-webkit-font-smoothing:subpixel-antialiased}.clearfix{clear:both;zoom:1}.clearfix:before,.clearfix:after{content:&quot;\0020&quot;;display:block;height:0;visibility:hidden}.clearfix:after{clear:both}

    </style>
    <style>
 .sign.error-page-wrapper {
    font-family: 'Source Sans Pro', sans-serif;
    background-color: #179eca;
    position:relative;
  }

 .sign.error-page-wrapper .sign-container {
    width:450px;
    height:415px;
    margin:0 auto;
    position: relative;
    transform:rotate(-20deg);
    text-indent:-20px;
  }


 .sign.error-page-wrapper .sign-container .nob {
    height:44px;
    width:44px;
    border-radius: 99px;
    border:12px solid #343c3f;
    position: absolute;
    top:0px;
    left:50%;
    margin-left:-22px;
  }

 .sign.error-page-wrapper .sign-container .post {
    transition:background-color .5s linear;
    width: 190px;
    height: 15px;
    top: 71px;
    background-color: #343c3f;
  }

 .sign.error-page-wrapper .sign-container .post.left {
    position: absolute;
    transform:rotate(-30deg);
    left:35px;
  }

 .sign.error-page-wrapper .sign-container .post.right {
    position: absolute;
    transform:rotate(30deg);
    right:35px;
  }

 .sign.error-page-wrapper .sign-container .pane {
    transition:background-color .5s linear, border-color .5s linear;
    box-shadow: 0 5px 0 rgba(0,0,0,.1) inset, 5px 0 0 rgba(0,0,0,.1) inset, 15px 15px 0 rgba(0,0,0,.1);
    background-color: #fff;
    border:20px solid #343c3f;
    height:300px;
    text-align: center;
    position: absolute;
    top: 115px;
    left:0px;
    right:0px;
  }

 .sign.error-page-wrapper .sign-container .pane .headline {
    transition:color .5s linear;
    margin-top:65px;
    margin-bottom: 10px;
    font-size:54px;
    line-height:68px;
    font-weight:600;
    letter-spacing: -2px;
    text-transform: uppercase;
    color:#ffba00;
  }

 .sign.error-page-wrapper .sign-container .pane.just-header .headline {
    margin-top:100px;
  }

 .sign.error-page-wrapper .sign-container .pane .context {
    transition:color .5s linear;
    color:#ffba00;
    font-size:24px;
    line-height: 32px;
  }


  @media screen and (max-width: 500px) {
    .sign.error-page-wrapper {
      padding-top:10%;
    }
    .sign.error-page-wrapper .sign-container {
      width:280px;
      top: 0px !important;
    }
    .sign.error-page-wrapper .sign-container .post {
      width:100px;
      top:50px;
    }
    .sign.error-page-wrapper .sign-container .pane {
      top:70px;
      height:220px;
    }
    .sign.error-page-wrapper .sign-container .pane .headline {
      margin-top:20px;
      font-size:45px;
      margin-bottom: 6px;
    }
    .sign.error-page-wrapper .sign-container .pane.just-header .headline {
      margin-top: 39px;
      line-height: 55px;
    }
    .sign.error-page-wrapper .sign-container .pane .context {
      font-size:20px;
      line-height: 28px;
    }
  }




 .sign.error-page-wrapper .text-container {
    max-width:425px;
    position: absolute;
    bottom:20px;
    left:35px;
  }

 .sign.error-page-wrapper .text-container .headline {
    transition:color .5s linear;
    font-size:40px;
    line-height: 52px;
    letter-spacing: -1px;
    margin-bottom: 5px;
    color:rgba(255,255,255,.3);
  }
 .sign.error-page-wrapper .text-container .context {
    transition:color .5s linear;
    font-size:18px;
    line-height:27px;
    color:#fff;
  }
 .sign.error-page-wrapper .text-container .context p {
    margin:0;
  }
 .sign.error-page-wrapper .text-container .context p + p {
    margin-top:10px;
  }
 .sign.error-page-wrapper .buttons-container {
    margin-top: 20px;
  }

 .sign.error-page-wrapper .buttons-container a {
    transition: text-indent .2s linear, color .5s linear, border-color .5s linear;
    font-size:16px;
    text-transform: uppercase;
    text-decoration: none;
    color:#fff;
    border:2px solid white;
    border-radius: 99px;
    padding:9px 0 10px;
    width:195px;
    overflow: hidden;
    text-align:center;
    display:inline-block;
    position: relative;
  }

 .sign.error-page-wrapper .buttons-container a:hover {
    background-color:rgba(255,255,255,.1);
    text-indent: 17px;
  }

 .sign.error-page-wrapper .buttons-container a:first-child {
    margin-right:25px;
  }

 .sign.error-page-wrapper .buttons-container .fa {
    transition:left .2s ease-out;
    position: absolute;
    left:-50px;
  }

 .sign.error-page-wrapper .buttons-container .fa-warning {
    font-size:16px;
    top:14px;
  }

 .sign.error-page-wrapper .buttons-container a:hover .fa-warning {
    left:0px;
  }

 .sign.error-page-wrapper .buttons-container .fa-power-off {
    font-size:16px;
    top:14px;
  }

 .sign.error-page-wrapper .buttons-container a:hover .fa-power-off {
    left:0px;
  }

 .sign.error-page-wrapper .buttons-container .fa-home {
    font-size:18px;
    top:12px;
  }

 .sign.error-page-wrapper .buttons-container a:hover .fa-home {
    left:25px;
  }

  @media screen and (max-width: 500px) {
   .sign.error-page-wrapper .text-container {
      bottom:20px;
      left:20px;
      right:20px;
    }
   .sign.error-page-wrapper .text-container .header {
      font-size:32px;
      line-height:40px;
    }
   .sign.error-page-wrapper .text-container .context {
      font-size:15px;
      line-height: 22px;
    }
   .sign.error-page-wrapper .buttons-container {
      overflow: hidden;
    }
   .sign.error-page-wrapper .buttons-container a {
      font-size:14px;
      padding:8px 0 9px;
      width:45%;
      float:left;
      margin:0;
    }
   .sign.error-page-wrapper .buttons-container a + a {
      float:right;
    }
   .sign.error-page-wrapper .buttons-container a:hover {
      text-indent: 0px;
    }
   .sign.error-page-wrapper .buttons-container .fa {
      display:none;
    }
  }
</style>
    <style>

    .background-color {
      background-color: rgba(235, 238, 240, 1) !important;
    }


    .primary-text-color {
      color: rgba(49, 55, 61, 1) !important;
    }

    .secondary-text-color {
      color: rgba(47, 108, 171, 1) !important;
    }

    .sign-text-color {
      color: rgba(255, 228, 119, 1) !important;
    }

    .sign-frame-color {
      color: #343C3F;
    }

    .pane {
      background-color: rgba(47, 108, 171, 1) !important;
    }

    .border-button {
      color: rgba(47, 108, 171, 1) !important;
      border-color: rgba(47, 108, 171, 1) !important;
    }
    .button {
      background-color: rgba(47, 108, 171, 1) !important;
      color: #FFFFFF !important;
    }

    .shadow {
      box-shadow: 0 0 60px #000000;
    }

</style>
  </head>
  <body class="sign error-page-wrapper background-color background-image">
    <div class="sign-container">
	<div class="nob"></div>
	<div class="post left"></div>
	<div class="post right"></div>
	<div class="pane">
		<div class="headline sign-text-color">
			403
		</div>
		<div class="context sign-text-color">
			There was issues submitting the form,<br>
			might be from csrf issues.
		</div>
	</div>
</div>
<div class="text-container">
	<div class="headline secondary-text-color">
		403
	</div>
	<div class="context primary-text-color">
		<p>
			This may be an error, or you may be up to something sneaky.
            If you think something is broken, report a problem.
		</p>
	</div>
	<div class="buttons-container">
		<a class="border-button" href="https://roundup.vesey.org/redirect/" target="_blank"><span class="fa fa-home"></span> Home Page</a>
	</div>
</div>

    <script>
      function ErrorPage(e,t,n){this.$container=$(e),this.$contentContainer=this.$container.find(n=="sign"?".sign-container":".content-container"),this.pageType=t,this.templateName=n}ErrorPage.prototype.centerContent=function(){var e=this.$container.outerHeight(),t=this.$contentContainer.outerHeight(),n=(e-t)/2,r=this.templateName=="sign"?-100:0;this.$contentContainer.css("top",n+r)},ErrorPage.prototype.initialize=function(){var e=this;this.centerContent(),this.$container.on("resize",function(t){t.preventDefault(),t.stopPropagation(),e.centerContent()}),this.templateName=="plain"&&window.setTimeout(function(){e.$contentContainer.addClass("in")},500),this.templateName=="sign"&&$(".sign-container").animate({textIndent:0},{step:function(e){$(this).css({transform:"rotate("+e+"deg)","transform-origin":"top center"})},duration:1e3,easing:"easeOutBounce"})},ErrorPage.prototype.createTimeRangeTag=function(e,t){return"<time utime="+e+' simple_format="MMM DD, YYYY HH:mm">'+e+"</time> - <time utime="+t+' simple_format="MMM DD, YYYY HH:mm">'+t+"</time>."},ErrorPage.prototype.handleStatusFetchSuccess=function(e,t){if(e=="503")$("#replace-with-fetched-data").html(t.status.description);else if(!t.scheduled_maintenances.length)$("#replace-with-fetched-data").html("<em>(there are no active scheduled maintenances)</em>");else{var n=t.scheduled_maintenances[0];$("#replace-with-fetched-data").html(this.createTimeRangeTag(n.scheduled_for,n.scheduled_until)),$.fn.localizeTime()}},ErrorPage.prototype.handleStatusFetchFail=function(e){$("#replace-with-fetched-data").html("<em>(enter a valid StatusPage.io url)</em>")},ErrorPage.prototype.fetchStatus=function(e,t){if(!e||!t||t=="404")return;var n="",r=this;t=="503"?n=e+"/api/v2/status.json":n=e+"/api/v2/scheduled-maintenances/active.json",$.ajax({type:"GET",url:n}).success(function(e,n){r.handleStatusFetchSuccess(t,e)}).fail(function(e,n){r.handleStatusFetchFail(t)})};
      var ep = new ErrorPage('body', "404", "sign");
      ep.initialize();

      // hack to make sure content stays centered >_<
      $(window).on('resize', function() {
        $('body').trigger('resize')
      });

    </script>
    
  </body>
</html>

templates/_admin_base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% include "_brandname.html" %} :: {% block title %}{% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="shortcut icon" href='{% static "site/images/favicon.ico" %}'>
  <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700'>
  <!-- FontAwesome http://fontawesome.io/ -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  {% block admin_override %}
  <link rel='stylesheet' href='{% static "site/css/admin.css" %}'>
  {% endblock admin_override %}

  <!-- jQuery library -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% block styles %}
  {% endblock styles %}

  {% block pagespecificstyles %}
  {% endblock pagespecificstyles %}

  <!-- Custom tags for the head tag -->
  {% block extrahead %}{% endblock extrahead %}

</head>
<body>

	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container-fluid">

                <!-- Brand/logo -->
                <div class="navbar-header">
                    <a class="navbar-brand navbar-logo"></a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-responsive-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand toggle-menu-btn"><i class="fa fa-bars"></i></a>
                </div>

                <!-- Collapsible Navbar -->
                <div class="collapse navbar-collapse" id="navbar-responsive-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'main_app:admin_logout' %}" id="logout">Log Out<span style="margin-left: 10px" class="fa fa-sign-out"></span></a></li>
                    </ul>
                </div>

            </div>
    </nav>

    <!-- Start of full page banner alerts (should relate to contents of entire page) -->
    {% block messages %}
    {% endblock %}
    {% block extra_messages %}
    {% endblock %}
    <!-- End full page Banner alert section -->

    <!-- Start of body content -->
    <div class="Page__Content" id="wrapper">
        <noscript>
            <div class="text-center">
                <p style="color: red;z-index:9999">You don't have javascript enabled.  Good luck with that.</p>
                <a target="_blank" href="https://www.google.com/search?q=How+to+enabled+JavaScript+in+browser%3F&oq=How+to+enabled+JavaScript+in+browser%3F&aqs=chrome..69i57j0l5.6842j0j7&sourceid=chrome&ie=UTF-8">
                    How to enable JavaScript in browser?</a>
            </div>
        </noscript>

        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" id="myAccordian">
                <li class="{% if active_menu == 'stores' %}activeMenu{%endif%}">
                    <a href="{% url 'main_app:admin_store_list' %}"><i class="fa fa-home"></i>Stores</a>
                </li>
                <li class="{% if active_menu == 'transfer' %}activeMenu{%endif%}" >
                    <a href="/admin/transfers"><i class="fa fa-exchange"></i>Invoices</a>
                </li>
                <li class="{% if active_menu == 'charity' %}activeMenu{%endif%}">
                    <a href="{% url 'main_app:admin_charity_list' %}"><i class="fa fa-heart"></i>Charities</a>
                </li>
            </ul>
        </div>

        <div id="page-content-wrapper">
            <div class="page-name">
            {% block breadcrumbs %}
                {% clear_breadcrumbs %}
            {% endblock %}
            {% render_breadcrumbs "django_bootstrap_breadcrumbs/bootstrap3.html" %}
            </div>
        {% block body %}{% endblock %}
        </div>
    </div>
    <!-- End of body content -->

    {% block extrafoot %}{% endblock extrafoot %}

    {% block pagespecificjs %}
    {% endblock pagespecificjs %}

    <script>
        $('.toggle-menu-btn').click(function ($event) {
            $event.stopPropagation();
            $("#wrapper").toggleClass("toggled");
        });
        function initMenu() {
            $('#myAccordion li a').on( "click", function () {
                $('.collapse.in').collapse('hide');
            });
        }
        $(document).ready(function () {
            initMenu();
        });
    </script>

    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/_admin_base_barren.html
<!DOCTYPE html>
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% include "_brandname.html" %} :: {% block title %}{% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="shortcut icon" href='{% static "site/images/favicon.ico" %}'>
  <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700'>
  <!-- FontAwesome http://fontawesome.io/ -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  {% block admin_override %}
  <link rel='stylesheet' href='{% static "site/css/admin.css" %}'>
  {% endblock admin_override %}

  <!-- jQuery library -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% block styles %}
  {% endblock styles %}

  {% block pagespecificstyles %}
  {% endblock pagespecificstyles %}

  <!-- Custom tags for the head tag -->
  {% block extrahead %}{% endblock extrahead %}

</head>
<body>

    <!-- Start of body content -->
    {% block body %}{% endblock %}

    {% block extrafoot %}{% endblock extrafoot %}

    {% block pagespecificjs %}
    {% endblock pagespecificjs %}

    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/_base_barren.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <script type="text/javascript" src="https://cdn.shopify.com/s/assets/external/app.js"></script>
  <script type="text/javascript">
        ShopifyApp.init({
            apiKey: '{{ SHOPIFY_APP_API_KEY }}',
            shopOrigin: 'https://{{ user.myshopify_domain }}'
        });
    </script>

    {% block styles %}
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

</head>
<body>

    <!-- Start of body content -->
    <div class="Page__Content">
        {% block body %}{% endblock %}
    </div>
    <!-- End of body content -->

    {% block extrafoot %}{% endblock extrafoot %}

    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/_brandname.html
Round Up - Support Local Non-Profits